### ISSUE TITLE
Should Webkit platform status be replaced by Webkit CSS feature status?

### ISSUE THREAD

**Issue by meduzen** [meduzen/canwe#109]
For some reason, https://webkit.org/status/ is retired, but https://webkit.org/css-status remains 🤷.

The message on https://webkit.org/status suggests to use MDN, Can I Use or the [Webkit Standards Positions repository](https://github.com/WebKit/standards-positions/issues).

**Comment by piraces** [comment]
Just came here to open this issue 😄 
I think the [Webkit Standards Positions repository](https://github.com/WebKit/standards-positions/issues) is a great alternative to this 👍

**Comment by meduzen** [comment]
Seems like https://webkit.org/css-status is outdated, so https://webkit.org/standards-positions/ would be the only one to keep for now. On it, and thanks for your message @piraces. 😄

**Comment by meduzen** [comment]
Deployed! 🚀

**Comment by piraces** [comment]
Thanks @meduzen !!
