### ISSUE TITLE
Wrong spacing between items in footer

### ISSUE THREAD

**Issue by meduzen** [meduzen/canwe#129]
😨

<img width="466" alt="image" src="https://github.com/meduzen/canwe/assets/9340937/81425e0e-853f-434c-846c-14095b756912">

<img width="448" alt="image" src="https://github.com/meduzen/canwe/assets/9340937/b61f1016-e919-4338-9f65-2f2342c42a2d">

**Comment by ankman007** [comment]
@meduzen Working on this issue. Will make a PR shortly.
