### ISSUE TITLE
Is Houdini Ready Yet?

### ISSUE THREAD

**Issue by Martin-Pitt** [meduzen/canwe#2]
I assume that any kind of dynamic 'question phrase' (can we/i, should we/i, is it ready?, …) site that pertains to web development/design is fair game here?

In this case, this one is maintained by @surma:
https://github.com/surma/ishoudinireadyyet.com
https://ishoudinireadyyet.com/

**Comment by meduzen** [comment]
Quoting myself in #5:

> My intent with _Can We_ was to propose websites based on **browsers usage data**, but maybe it could be widened to other resources answering the “can we?” question. 🤔

Is Houdini Read Yet fits. 👍
