### ISSUE TITLE
I Want To Use 

### ISSUE THREAD

**Issue by Martin-Pitt** [meduzen/canwe#3]
This website is nifty
http://www.iwanttouse.com/

However, looks like it has been unmaintained by @PaulKinlan and the reporting has gone inaccurate:
https://github.com/PaulKinlan/iwanttouse.com/issues/7

**Comment by meduzen** [comment]
This is a cool one indeed, but as the data aren’t accurate (probably because unmaintained), it would be misleading to add it.

Closing this. Thanks for all the issues. 🙏
