### ISSUE TITLE
What's Next For CSS?

### ISSUE THREAD

**Issue by Martin-Pitt** [meduzen/canwe#5]
What’s next for CSS?
cssdb is a comprehensive list of CSS features and their positions in the process of becoming implemented web standards:
https://cssdb.org/

It seems to be consistently maintained over time by @jonathantneal for years

**Comment by meduzen** [comment]
Indeed a great one!

My intent with _Can We_ was to propose websites based on **browsers usage data**, but maybe it could be widened to other resources answering the “can we?” question. 🤔

(Maybe I’m biased because I’m a [postcss-preset-env](https://preset-env.cssdb.org) fan, but I’ll seriously consider this.)

**Comment by meduzen** [comment]
Hi @Martin-Pitt!

Here’s a preview of _Can We_ with #2 and #5 added in a separate category [maybe.canwe.dev](https://maybe.canwe.dev).

I’d like to have your opinion before [merging](8): do you think it’s acceptable and clear enough?

**Comment by Martin-Pitt** [comment]
Hmm, seems a bit at odd with whocanuse which doesn't use browser usage data at all, but the other two do?

**Comment by meduzen** [comment]
There’s indeed something messy in the current classification. It’s more like:
- some websites have data about how many people may be concerned (Can I Use, Can I Stop, Who Can Use)
- others are strictly about features and don’t have any data.

But at the end, all of them help to shape answers to the many “can we” questions developers have.

Maybe they don’t need to be classified, or at least not that way but I don’t know how. 🕳
