### ISSUE TITLE
Chrome, Firefox and WebKit  Platform/Feature Status?

### ISSUE THREAD

**Issue by Martin-Pitt** [meduzen/canwe#6]
It's not setup as a phrased question, but these are very useful resources in the same line as caniuse — although pertain more to the feature roadmaps of the browser engines and their progress.

https://chromestatus.com/
https://platform-status.mozilla.org/
https://webkit.org/status/

**Comment by meduzen** [comment]
Also, Microsoft platform status (https://developer.microsoft.com/en-us/microsoft-edge/platform/status).

**Comment by Martin-Pitt** [comment]
I had left that out intentionally at first, since I know that Microsoft Edge is still moving over to a Chromium code-base. But looking at list in detail again, it seems fine and usable. 👍
